name: Damn Vulnerable Web Application
base_url: http://localhost:8081

authentication:
  type: form
  username: "admin"
  password: "password"
  login:
    url: /login.php
    method: POST
    payload:
      username: "{{AUTH_USERNAME}}"
      password: "{{AUTH_PASSWORD}}"
      Login: "Login"
    headers:
      Content-Type: application/x-www-form-urlencoded
    apply:
      cookies:
        security: "low"

endpoints:
  base: /
  custom:
    # Generic template endpoint mappings
    sqli: /vulnerabilities/sqli/?id=1&Submit=Submit
    sqli_post: /vulnerabilities/sqli/
    command_injection: /vulnerabilities/exec/?127.0.0.1
    xss_reflected: /vulnerabilities/xss_r/?name=
    xss_stored: /vulnerabilities/xss_s/
    path_traversal: /vulnerabilities/fi/?page=
    ssrf: /vulnerabilities/ssrf/?page=

timeout: 30.0
parallel: 5
