name: educacion.us.es
base_url: https://educacion.us.es

authentication:
  type: none

endpoints:
  base: /
  custom:
    # Joomla CMS search endpoint (main injection point)
    sqli: /component/search/?searchword=
    sqli_post: /
    command_injection: /component/search/?searchword=
    xss_reflected: /component/search/?searchword=
    xss_stored: /
    path_traversal: /component/search/?searchword=
    ssrf: /component/search/?searchword=

variables:
  USER_EMAIL: "test@example.com"
  USER_PASSWORD: "Test123!"

timeout: 30.0
parallel: 3
